version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NOVITA_API_KEY=sk_ceB46ZBdon6SGm2dQHeHSVHfSpmghj9IOR10W2mY6Ao